/*
MIT License

Copyright (c) 2024 Tobias Staack

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#pragma once

#include <websocket/core/byte_stream.h>

#include <string>

#include <websocket/defs/socketDefs.h>

/** \cond */

/**
 * @class c_ws_handshake
 * @brief Builds and validates the opening handshake of RFC 6455 section 4.
 *
 * The handshake may arrive across several segments, so the reading methods report
 * `busy` until the field block is complete and only then accept or reject it.
 */
class c_ws_handshake final
{
public:
    /**
     * @enum e_status
     * @brief Outcome of a handshake operation.
     */
    enum e_status : unsigned char
    {
        ok = 0x0, /**< operation was successful. */
        error = 0x1, /**< an error occurred during the operation. */
        busy = 0x2 /**< the socket is currently busy. */
    };

    /**
     * @brief Produces a block of cryptographically strong random bytes.
     *
     * @param[in] count Number of bytes to generate.
     * @param[out] output Receives the generated bytes.
     * @return `ok` on success, `error` when no entropy could be obtained.
     */
    static e_status
    random( size_t count, std::string &output );

    /**
     * @brief Derives the `Sec-WebSocket-Accept` value from a `Sec-WebSocket-Key`.
     *
     * Appends the GUID of RFC 6455 section 1.3, hashes the result with SHA-1 and
     * encodes it as base64.
     *
     * @param[in] input The `Sec-WebSocket-Key` field value sent by the client.
     * @param[out] output Receives the accept value.
     * @return `ok` on success, `error` when the digest could not be computed.
     */
    static e_status
    secret( const std::string &input, std::string &output );

    /**
     * @brief Builds the client handshake request.
     *
     * @param[in] host Authority to send as `Host`.
     * @param[in] origin Origin to send, an empty string omits the field.
     * @param[in] channel Resource name to request, an empty string requests "/".
     * @param[in] sub_protocols Comma separated subprotocols to offer, may be empty.
     * @param[out] output Receives the request bytes.
     * @param[out] out_accept_key Receives the accept value the server has to answer with.
     * @param[in] extensions Extensions to offer, may be NULL.
     * @return `ok` on success, `error` when the request could not be built.
     */
    static e_status
    create( const char *host, const char *origin, const char *channel, const char *sub_protocols, c_byte_stream *output, std::string &out_accept_key, const ws_extensions_t *extensions );

    /**
     * @brief Validates the server handshake response on the client side.
     *
     * @param[in] accept_key The accept value returned by `create`.
     * @param[in] sub_protocols The subprotocols that were offered, may be empty.
     * @param[in] input Stream holding the response, consumed once complete.
     * @param[out] output Receives an error response when the exchange fails.
     * @param[in] offered_extensions The extensions that were offered, may be NULL.
     * @param[out] extensions Receives the negotiated extensions, may be NULL.
     * @param[out] out_sub_protocol Receives the agreed subprotocol, empty when none was agreed.
     * @return `ok` when the connection is established, `busy` while the response is incomplete, `error` otherwise.
     */
    static e_status
    client( const char *accept_key, const char *sub_protocols, const c_byte_stream *input, c_byte_stream *output, const ws_extensions_t *offered_extensions, ws_extensions_t *extensions, std::string &out_sub_protocol );

    /**
     * @brief Validates the client handshake request and writes the response on the server side.
     *
     * @param[in] host Authority the server accepts, without a port any port matches.
     * @param[in] origin Origin the server accepts, an empty string disables the check.
     * @param[in] sub_protocols Comma separated subprotocols the server supports, may be empty.
     * @param[in] input Stream holding the request, consumed once complete.
     * @param[out] output Receives the response, either the upgrade or an error status.
     * @param[in] server_extensions Extensions the server is willing to use, may be NULL.
     * @param[out] client_extensions Receives the negotiated extensions, may be NULL.
     * @param[out] out_sub_protocol Receives the agreed subprotocol, empty when none was agreed.
     * @return `ok` when the connection is established, `busy` while the request is incomplete, `error` otherwise.
     */
    static e_status
    server( const char *host, const char *origin, const char *sub_protocols, const c_byte_stream *input, c_byte_stream *output, const ws_extensions_t *server_extensions, ws_extensions_t *client_extensions, std::string &out_sub_protocol );
};
/** \endcond */
